# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"\x1a\n\tFrameSend\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"#\n\rFrameResponse\x12\x12\n\ncamera_off\x18\x01 \x01(\x08\x32\x35\n\x0cImageService\x12%\n\x05Image\x12\n.FrameSend\x1a\x0e.FrameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMESEND']._serialized_start=15
  _globals['_FRAMESEND']._serialized_end=41
  _globals['_FRAMERESPONSE']._serialized_start=43
  _globals['_FRAMERESPONSE']._serialized_end=78
  _globals['_IMAGESERVICE']._serialized_start=80
  _globals['_IMAGESERVICE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
